#∂Àø⁄
server:
  port: 9999

#mysql≈‰÷√
spring:
  datasource:
    url: jdbc:mysql://111.231.110.198:3306/eje-online?useUnicode=true&characterEncoding=utf-8
    username: root
    password: _Lyj112233
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

#mybatisŒª÷√
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  type-aliases-package: com.sgcc.zj.common.entity
